# Generated by Django 5.0.6 on 2026-04-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('assunto', models.CharField(choices=[('Reserva de Moeda', 'Reserva de Moeda'), ('Western Union', 'Western Union'), ('Compra de Ouro', 'Compra de Ouro'), ('Crédito Pessoal', 'Crédito Pessoal'), ('Empresas', 'Empresas'), ('Outro', 'Outro')], default='Outro', max_length=100, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telemovel', models.CharField(max_length=30, verbose_name='Telemóvel')),
                ('moeda', models.CharField(max_length=100, verbose_name='Moeda')),
                ('montante', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montante (EUR)')),
                ('data_levantamento', models.DateField(verbose_name='Data de levantamento')),
                ('balcao', models.CharField(max_length=200, verbose_name='Balcão preferido')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('levantada', 'Levantada')], default='pendente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
